Implement Peak Annotation Parser
HUPO-PSI/mzSpecLib pull request #28
Opened 2021-01-29 02:15 UTC by mobiusklein

Implements the peak annotation parser/writer, which can be converted to the data model in JSON and round-tripping to and from JSON as well as the string form.

## Annotation Parsing
The regular expression to parse peak annotations is in `mzlib.annotation.annotation_pattern`, which is a beast. It uses PCRE named capture and non-capturing group syntax plus verbose mode to make it span multiple lines. A comment below shows the fully ECMAScript Regex compatible version on a single line, which at the time of writing is 656 characters. 

The `mzlib.annotation.parse_annotation` functor handles the process, calling it converts a string to a list of `IonAnnotationBase` objects, and it encapsulates the parsing and type coercion process.

`IonAnnotationBase` subclasses for all of the ion series types exist, and they map directly onto the data model JSONSchema. Their instances coerce to JSON and pass the schema check too.

Places where the abstraction leaks:
1. `[]` wrapping the annotation isn't handled by a regex because there are nested `[]` within the pattern, and that makes it not-regular. This is handled within the `mzlib.annotation.parse_annotation` implementation. "auxiliary"-ness isn't reflected in the data model anywhere because I overlooked it during the initial slotting. 
2. All formulae are just "dumb" strings. Will need to eventually coerce them to first class objects which know some basic chemistry for mass calculation, and define what the notation for isotopes is. Same story for adducts.
3. Repeat 2, but for modifications, which have to go through a bit more coercion. Right now we're only consuming MSP files which means MSP-written modifications are copied verbatim.

## Integration with Format Backends
### MSP
The `msp` backend has a specialized parser with its own regex and parser designed to parse the idiosyncrasies where the actual sequence is needed to resolve what the annotation is (e.g. internal peptide fragments).

### Text
The `text` backend directly uses `parse_annotation` to parse annotations.

### JSON
The `json` backend either uses `parse_annotation` when the `interpretations` array contains strings, or `IonAnnotationBase.from_json` when they are parsed `list`/`dict` objects.

The JSON writer exposes a `format_annotations` parameter which controls whether the `interpretations` array will be filled with strings or the JSON-formatted data model.

2021-01-29 17:18 UTC, RalfG requested changes

2021-02-12 02:47 UTC, bittremieux approved these changes
I didn't do a fully in-depth review because I'm not familiar enough with the code, but in general it looks good.

2021-03-25 15:42 UTC, RalfG approved these changes
This PR also updates the dev branch to recent changes in master, so more changes are listed here than are actually part of the PR. When this is merged, we should pull dev into master, so everything is up-to-date again. 

We can consider to drop this separate dev branch. The only advantage of having separate master and dev branches is that you can always keep master branch as stable, which is not really relevant yet for this repo.

2021-05-07 15:48 UTC, edeutsch approved these changes

2021-05-07 15:48 UTC, merged